#if defined _discord_included_
  #endinput
#endif
#define _discord_included_

#pragma dynamic 32768;

#include <json>
#include <DateTime>

#include <discord_smjson/DiscordTypeExtensions>
#include <discord_smjson/DiscordPermission>
#include <discord_smjson/DiscordGatewayPayload>
#include <discord_smjson/DiscordActivity>
#include <discord_smjson/DiscordPresence>
#include <discord_smjson/DiscordException>
#include <discord_smjson/DiscordBot>
#include <discord_smjson/DiscordRequest>
#include <discord_smjson/DiscordWebHook>
#include <discord_smjson/DiscordObject>
#include <discord_smjson/DiscordAttachment>
#include <discord_smjson/DiscordRole>
#include <discord_smjson/DiscordUser>
#include <discord_smjson/DiscordEmoji>
#include <discord_smjson/DiscordGuildUser>
#include <discord_smjson/DiscordVoiceRegion>
#include <discord_smjson/DiscordChannel>
#include <discord_smjson/DiscordChannelMention>
#include <discord_smjson/DiscordGuild>
#include <discord_smjson/DiscordReaction>
#include <discord_smjson/DiscordMessage>